version: "3.7"
services:
  client:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    volumes:
      - ./client:/client
    ports:
      - 8000:8000
      - 80:9000
    command: ["gatsby", "develop", "-H", "0.0.0.0"]
